# Usa uma imagem oficial do Python como base
FROM python:3.11

# Define o diretório de trabalho no contêiner
WORKDIR /app

# Copia os arquivos do projeto para o contêiner
COPY . .

# Atualiza e instala dependências do sistema (se necessário)
RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

# Instala as dependências do projeto
RUN pip install --no-cache-dir -r requirements.txt

# Instala o Gunicorn separadamente (garante que está instalado)
RUN pip install --no-cache-dir gunicorn

# Expõe a porta 8000
EXPOSE 8000

# Comando para iniciar o servidor Django
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "setupIA.wsgi:application"]
